-- 코드를 입력하세요
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE*C.SALES) AS SALES
FROM BOOK A
    JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
    JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
WHERE C.SALES_DATE LIKE "2022-01%"
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY 1 ASC, 3 DESC

# SELECT sum(C.PRICE*A.SALES) AS SALES
# FROM BOOK_SALES A
#     LEFT JOIN BOOK C ON A.BOOK_ID = C.BOOK_ID
#     LEFT JOIN AUTHOR B ON B.AUTHOR_ID = B.AUTHOR_ID
# WHERE A.SALES_DATE LIKE "2022-01%"
# GROUP BY B.AUTHOR_ID, C.CATEGORY
# ORDER BY B.AUTHOR_ID, C.CATEGORY
