-- 코드를 입력하세요
SELECT 
    C.AUTHOR_ID, C.AUTHOR_NAME, B.CATEGORY, SUM(A.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK_SALES A 
    JOIN BOOK B USING(BOOK_ID) 
    JOIN AUTHOR C USING(AUTHOR_ID)
WHERE 
    SALES_DATE LIKE "2022-01%"
GROUP BY 
    B.AUTHOR_ID, 
    C.AUTHOR_NAME, 
    B.CATEGORY
ORDER BY 
    1 , 3 DESC