SELECT 
    B.AUTHOR_ID, 
    C.AUTHOR_NAME, 
    B.CATEGORY, 
    SUM(A.SALES * B.PRICE) AS TOTAL_SALES
FROM 
    BOOK_SALES A
    JOIN BOOK B USING (BOOK_ID)
    JOIN AUTHOR C USING (AUTHOR_ID)
WHERE 
    A.SALES_DATE LIKE '2022-01%'
GROUP BY 
    B.AUTHOR_ID, 
    C.AUTHOR_NAME, 
    B.CATEGORY
ORDER BY 
    B.AUTHOR_ID ASC, 
    B.CATEGORY DESC;
