WITH YOGURT AS (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
)
# SELECT 
# FROM CART_PRODUCTS
# WHERE CART_ID IN (SELECT CART_ID FROM YOGURT WHERE NAME = 'Yogurt')


# SELECT CART_ID
# FROM CART_PRODUCTS
# WHERE CART_ID IN (SELECT CART_ID FROM YOGURT WHERE NAME = 'Yogurt') AND NAME = 'Milk'


SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Yogurt', 'Milk')
GROUP BY CART_ID
HAVING COUNT(DISTINCT(NAME)) >= 2
ORDER BY CART_ID

