-- 코드를 입력하세요
WITH LIST AS (
    SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR A lEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
    WHERE A.CAR_TYPE IN ("SUV", "세단") AND A.CAR_ID NOT IN (
            SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE <= '2022-11-30'
              AND END_DATE   >= '2022-11-01'
      )
)
SELECT DISTINCT(A.CAR_ID) AS CAR_ID, A.CAR_TYPE, (FLOOR(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100)
) AS FEE
FROM LIST A JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN  B ON A.CAR_TYPE = B.CAR_TYPE 
WHERE B.DURATION_TYPE = "30일 이상" AND FLOOR(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100)
 >= 500000 AND FLOOR(A.DAILY_FEE * 30 * (100 - B.DISCOUNT_RATE) / 100)
< 2000000 
ORDER BY FEE DESC, A.CAR_TYPE ASC , CAR_ID DESC  

# SELECT * 
# FROM LIST