-- 코드를 작성해주세요
WITH RANKED AS (
    SELECT ID, SIZE_OF_COLONY, ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS 'RANK'
    FROM ECOLI_DATA 
)

SELECT R.ID,
    (CASE
        WHEN R.RANK <= (COUNT(*) OVER() * 0.25) THEN "CRITICAL"
        WHEN R.RANK <= (COUNT(*) OVER() * 0.50) THEN "HIGH"
        WHEN R.RANK <= (COUNT(*) OVER() * 0.75) THEN "MEDIUM"
        ELSE "LOW"
    END) AS 'COLONY_NAME'
FROM RANKED R
ORDER BY R.ID