-- 코드를 작성해주세요
WITH LIST AS (
    SELECT ID, COUNT(*) OVER() AS CNT, ROW_NUMBER() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RANKED
    FROM ECOLI_DATA
)
SELECT ID,
    CASE
        WHEN RANKED <= cnt/4 THEN "CRITICAL"
        WHEN RANKED <= cnt/2 THEN "HIGH"
        WHEN RANKED <= (cnt*3)/4 THEN "MEDIUM"
        ELSE "LOW"        
    END AS COLONY_NAME
FROM LIST
ORDER BY 1

