-- 코드를 입력하세요
WITH LIST AS (SELECT A.USER_ID AS USER_ID , A.GENDER AS GENDER, YEAR(B.SALES_DATE) AS YEAR, MONTH(B.SALES_DATE) AS MONTH
FROM USER_INFO A JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
)

SELECT A.YEAR, A.MONTH, A.GENDER, COUNT(DISTINCT(A.USER_ID)) AS USERS
# SELECT A.YEAR, A.MONTH, A.GENDER, 
FROM LIST A
GROUP BY A.YEAR, A.MONTH, A.GENDER
ORDER BY A.YEAR, A.MONTH, A.GENDER