-- 코드를 입력하세요
# SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE, START_DATE)+1),1) AS AVERAGE_DURATION
SELECT A.CAR_ID, ROUND(AVG(A.DURATION),1)  AS AVERAGE_DURATION
FROM (
    SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY  
) A
GROUP BY CAR_ID
HAVING AVG(A.DURATION) >= 7
ORDER BY 2 DESC , 1 DESC