-- 코드를 입력하세요
SET @total = (SELECT COUNT(*) FROM USER_INFO WHERE JOINED LIKE "2021%");


SELECT YEAR(B.SALES_DATE), MONTH(B.SALES_DATE), COUNT(DISTINCT(A.USER_ID)) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT(A.USER_ID))/@total, 1) AS PUCHASED_RATIO
FROM USER_INFO A LEFT JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID 
WHERE JOINED LIKE "2021%" AND YEAR(B.SALES_DATE) IS NOT NULL
GROUP BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE)
ORDER BY YEAR(B.SALES_DATE), MONTH(B.SALES_DATE)


