SELECT 

    B.HISTORY_ID,
    ROUND(
        A.DAILY_FEE * (DATEDIFF(B.END_DATE, B.START_DATE)+1) 
        * (1 - IFNULL(C.DISCOUNT_RATE, 0) / 100)
    ) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR A
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B ON A.CAR_ID = B.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C 
        ON A.CAR_TYPE = C.CAR_TYPE
        AND (
            (C.DURATION_TYPE = '7일 이상' AND DATEDIFF(B.END_DATE, B.START_DATE)+1 BETWEEN 7 AND 29)
            OR (C.DURATION_TYPE = '30일 이상' AND DATEDIFF(B.END_DATE, B.START_DATE)+1 BETWEEN 30 AND 89)
            OR (C.DURATION_TYPE = '90일 이상' AND DATEDIFF(B.END_DATE, B.START_DATE)+1 >= 90)
        )
WHERE 
    A.CAR_TYPE = '트럭'
ORDER BY 
    FEE DESC,
    B.HISTORY_ID DESC;