SELECT A.APNT_NO,  C.PT_NAME, A.PT_NO, A.MCDP_CD,B.DR_NAME, A.APNT_YMD 
FROM APPOINTMENT A 
LEFT OUTER JOIN DOCTOR B ON A.MDDR_ID = B.DR_ID
LEFT OUTER JOIN PATIENT C ON A.PT_NO = C.PT_NO
WHERE A.MCDP_CD = 'CS' AND A.APNT_CNCL_YN = 'N' AND YEAR(A.APNT_YMD) = 2022 AND MONTH(A.APNT_YMD) = 4 AND DAY(A.APNT_YMD) = 13
ORDER BY A.APNT_YMD
