-- 코드를 입력하세요
WITH RECURSIVE HOURS AS(
    SELECT 0 AS 'HOUR'
    UNION ALL
    SELECT HOUR+1 
    FROM HOURS
    WHERE HOUR < 23
),
COUNTS AS (
    SELECT HOUR(A.DATETIME) AS HOUR, COUNT(*) AS CNT
    FROM ANIMAL_OUTS A 
    GROUP BY HOUR(A.DATETIME)
)




SELECT A.HOUR, IFNULL(CNT, 0)
FROM HOURS A LEFT JOIN COUNTS B ON A.HOUR = B.HOUR
GROUP BY A.HOUR