-- 코드를 입력하세요
SELECT A.USER_ID, A.NICKNAME, B.TOTAL_SALES
FROM USED_GOODS_USER A JOIN(
        SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
        FROM USED_GOODS_BOARD 
        WHERE STATUS = 'DONE'
        GROUP BY WRITER_ID) B
        ON B.WRITER_ID = A.USER_ID
WHERE TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES

# SELECT B.USER_ID, B.NICKNAME, A.PRICE AS TOTAL_SALES
# FROM USED_GOODS_BOARD A JOIN USED_GOODS_USER B  ON A.WRITER_ID = B.USER_ID
# WHERE A.PRICE >= 700000 AND A.STATUS = 'DONE'
# ORDER BY A.PRICE