-- 코드를 입력하세요
WITH RANKED AS(SELECT A.MEMBER_ID, RANK() OVER(ORDER BY COUNT(*) DESC) AS `RANK`
FROM REST_REVIEW A 
GROUP BY A.MEMBER_ID)

SELECT C.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
# SELECT * 
FROM RANKED A 
    JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID 
    JOIN MEMBER_PROFILE C ON A.MEMBER_ID = C.MEMBER_ID 
WHERE A.RANK = 1
ORDER BY 3 ASC, 2 ASC 



