-- 코드를 입력하세요
SELECT A.ANIMAL_ID AS ANIMAL_ID, A.NAME AS NAME
# SELECT *
FROM ANIMAL_INS A JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE DATEDIFF(B.DATETIME, A.DATETIME) < 0
WHERE B.DATETIME < A.DATETIME
ORDER BY A.DATETIME