-- 코드를 작성해주세요
SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
# SELECT *
FROM DEVELOPERS A JOIN SKILLCODES B ON A.SKILL_CODE & B.CODE = B.CODE
WHERE B.NAME IN ("Python", "C#")
GROUP BY A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
ORDER BY A.ID