-- 코드를 작성해주세요
SELECT YEAR(B.DIFFERENTIATION_DATE) AS YEAR, (MAX_TABLE.MAX_SIZE-B.SIZE_OF_COLONY) AS YEAR_DEV, B.ID
FROM (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR , MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)) MAX_TABLE JOIN ECOLI_DATA B ON MAX_TABLE.YEAR = YEAR(B.DIFFERENTIATION_DATE)
ORDER BY 1, 2