WITH LIST AS(
    SELECT *, RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS ranked
    FROM FISH_INFO
)

SELECT A.ID AS ID, B.FISH_NAME, A.LENGTH
FROM LIST A JOIN FISH_NAME_INFO B ON A.FISH_TYPE = B.FISH_TYPE
WHERE ranked = 1
ORDER BY ID 
