-- 코드를 작성해주세요
WITH RESULT AS(
SELECT ID,FISH_TYPE, LENGTH, RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS "RANK"
FROM FISH_INFO
)

SELECT R.ID, B.FISH_NAME, R.LENGTH
FROM RESULT R JOIN FISH_NAME_INFO B ON R.FISH_TYPE = B.FISH_TYPE
wHERE R.RANK = 1
ORDER BY 1