-- 코드를 작성해주세요
WITH SALARY AS (SELECT B.DEPT_NAME_EN , ROUND(AVG(A.SAL),0) AS AVG_SAL
FROM HR_EMPLOYEES A JOIN HR_DEPARTMENT B ON A.DEPT_ID = B.DEPT_ID
GROUP BY B.DEPT_NAME_EN)

SELECT A.DEPT_ID, A.DEPT_NAME_EN ,B.AVG_SAL 
FROM HR_DEPARTMENT A JOIN SALARY B ON A.DEPT_NAME_EN = B.DEPT_NAME_EN
ORDER BY 3 DESC