-- 코드를 입력하세요
SELECT CATEGORY, SUM(SALES) AS TOTAL_SALES
FROM BOOK A INNER JOIN BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID
WHERE MONTH(B.SALES_DATE) = 1 AND YEAR(B.SALES_DATE) = 2022
GROUP BY A.CATEGORY
ORDER BY A.CATEGORY