-- 코드를 입력하세요
WITH RANKED AS(
    SELECT CATEGORY, PRICE, PRODUCT_NAME, RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS 'RANK'
    FROM FOOD_PRODUCT 
)

SELECT R.CATEGORY, R.PRICE AS MAX_PRICE, R.PRODUCT_NAME 
FROM RANKED R
WHERE R.RANK = 1 AND R.CATEGORY IN ("과자", "국", "김치", "식용유")
ORDER BY 2 DESC