WITH FISH_SIZE AS(
    SELECT A.FISH_TYPE
    FROM (SELECT FISH_TYPE, IFNULL(LENGTH, 10) AS LENGTH
         FROM FISH_INFO 
         ) A
    GROUP BY A.FISH_TYPE 
    HAVING AVG(A.LENGTH) >= 33
)

SELECT COUNT(*) FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM FISH_INFO
WHERE FISH_TYPE IN (SELECT FISH_TYPE FROM FISH_SIZE)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE

