-- 코드를 작성해주세요
WITH LIST AS (
    SELECT id, FISH_TYPE, IFNULL(LENGTH, 10) as len
    FROM FISH_INFO
)

SELECT COUNT(*) as FISH_COUNT  , MAX(len) AS MAX_LENGTH, FISH_TYPE
FROM LIST
GROUP BY FISH_TYPE
HAVING AVG(len) >= 33
ORDER BY 3