


SELECT count(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM (
  SELECT FISH_TYPE, ID, IFNULL(LENGTH, 10) AS LENGTH
  FROM FISH_INFO
) A
WHERE FISH_TYPE IN (
  SELECT FISH_TYPE
  FROM (
    SELECT FISH_TYPE, AVG(IFNULL(LENGTH, 10)) AS avg_length
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING avg_length >= 33
  ) B
)
GROUP BY FISH_TYPE
ORDER BY FISH_TYPE
